USE Sample1;
CREATE TABLE CUSTOMER(
CUSTOMER_id INT ,
CUSTOMER_name VARCHAR(30),
City VARCHAR(10),
Grade INT,
Salesman_id INT);

DESCRIBE CUSTOMER;

INSERT INTO CUSTOMER VALUE
(3002,"NICK RIMANDO","NEW YORK",100,5001),
(3005,"GRAHAM ZUSI","CALIFORNIA",200,5002);

INSERT INTO CUSTOMER(CUSTOMER_id,CUSTOMER_name,City)VALUE
(3001,"BRAD GUZAN","LONDAN");

INSERT INTO CUSTOMER VALUE
(3004,"FABIAN JOHNS","PARIS",300,5006),
(3007,"BRAD DAVIS","NEW YORK",200,5001);

INSERT INTO CUSTOMER(CUSTOMER_id,CUSTOMER_name,City,Grade)VALUE
(3009,"GEOFF CAMERO","BERLIN",100);

INSERT INTO CUSTOMER VALUE
(3008,"JULAN GREEN","LANDON",300,5002),
(3003,"JOZY ALTIDOR","MONCOW",200,5007);

SELECT * FROM CUSTOMER;

SELECT * FROM CUSTOMER
WHERE Grade=200;

SELECT * FROM CUSTOMER
WHERE  City="NEW YORK" OR NOT Grade>100 ;

SELECT * FROM CUSTOMER
WHERE CUSTOMER_name LIKE "%N";

SELECT * FROM CUSTOMER
WHERE Grade IS NULL;

SELECT City,MAX(Grade) FROM CUSTOMER;




